# Generated by Django 3.0.5 on 2020-05-06 03:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名前')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='図鑑番号')),
                ('type1', models.IntegerField(choices=[(1, 'ノーマル'), (2, 'ほのお'), (3, 'みず'), (4, 'でんき'), (5, 'くさ'), (6, 'こおり'), (7, 'かくとう'), (8, 'どく'), (9, 'じめん'), (10, 'ひこう'), (11, 'エスパー'), (12, 'むし'), (13, 'いわ'), (14, 'ゴースト'), (15, 'ドラゴン'), (16, 'あく'), (17, 'はがね'), (18, 'フェアリー')], verbose_name='タイプ１')),
                ('type2', models.IntegerField(blank=True, choices=[(1, 'ノーマル'), (2, 'ほのお'), (3, 'みず'), (4, 'でんき'), (5, 'くさ'), (6, 'こおり'), (7, 'かくとう'), (8, 'どく'), (9, 'じめん'), (10, 'ひこう'), (11, 'エスパー'), (12, 'むし'), (13, 'いわ'), (14, 'ゴースト'), (15, 'ドラゴン'), (16, 'あく'), (17, 'はがね'), (18, 'フェアリー')], null=True, verbose_name='タイプ２')),
                ('charac1', models.CharField(max_length=50, verbose_name='とくせい１')),
                ('charac2', models.CharField(blank=True, max_length=50, null=True, verbose_name='とくせい２')),
                ('charac3', models.CharField(blank=True, max_length=50, null=True, verbose_name='夢とくせい')),
                ('h', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='H')),
                ('a', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='A')),
                ('b', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='B')),
                ('c', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='C')),
                ('d', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='D')),
                ('s', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='S')),
            ],
            options={
                'verbose_name': 'アイテム',
                'verbose_name_plural': 'アイテム',
            },
        ),
    ]
