# Generated by Django 3.0.5 on 2020-05-06 06:38

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='a',
        ),
        migrations.RemoveField(
            model_name='item',
            name='b',
        ),
        migrations.RemoveField(
            model_name='item',
            name='c',
        ),
        migrations.RemoveField(
            model_name='item',
            name='charac1',
        ),
        migrations.RemoveField(
            model_name='item',
            name='charac2',
        ),
        migrations.RemoveField(
            model_name='item',
            name='charac3',
        ),
        migrations.RemoveField(
            model_name='item',
            name='d',
        ),
        migrations.RemoveField(
            model_name='item',
            name='h',
        ),
        migrations.RemoveField(
            model_name='item',
            name='s',
        ),
        migrations.RemoveField(
            model_name='item',
            name='type1',
        ),
        migrations.RemoveField(
            model_name='item',
            name='type2',
        ),
        migrations.AddField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='登録日'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='memo',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='備考'),
        ),
        migrations.AddField(
            model_name='item',
            name='sex',
            field=models.IntegerField(choices=[(1, '男性'), (2, '女性')], default=1, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='item',
            name='age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='年齢'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=200, verbose_name='名前'),
        ),
    ]
