# Generated by Django 3.0.5 on 2020-05-06 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_item_type2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='created_at',
        ),
    ]
