# Generated by Django 3.0.5 on 2020-05-06 09:59

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_item_type2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='no',
        ),
        migrations.RemoveField(
            model_name='item',
            name='type1',
        ),
        migrations.AddField(
            model_name='item',
            name='age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='年齢'),
        ),
        migrations.AddField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='登録日'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='sex',
            field=models.IntegerField(choices=[(1, '男性'), (2, '女性')], default=1, verbose_name='性別'),
        ),
    ]
