# Generated by Django 3.0.5 on 2020-05-06 10:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200506_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='age',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sex',
        ),
        migrations.AddField(
            model_name='item',
            name='no',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='図鑑番号'),
        ),
        migrations.AddField(
            model_name='item',
            name='type1',
            field=models.IntegerField(choices=[(1, 'ノーマル'), (2, 'ほのお'), (3, 'みず'), (4, 'でんき'), (5, 'くさ'), (6, 'こおり'), (7, 'かくとう'), (8, 'どく'), (9, 'じめん'), (10, 'ひこう'), (11, 'エスパー'), (12, 'むし'), (13, 'いわ'), (14, 'ゴースト'), (15, 'ドラゴン'), (16, 'あく'), (17, 'はがね'), (18, 'フェアリー')], default=1, verbose_name='タイプ'),
        ),
    ]
