# Generated by Django 3.0.5 on 2020-05-06 10:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200506_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='h',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='H'),
        ),
    ]
