# Generated by Django 3.0.5 on 2020-05-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200506_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='charac1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='とくせい１'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=50, verbose_name='名前'),
        ),
    ]
