# Generated by Django 3.0.5 on 2020-05-09 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200506_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='charac1',
            new_name='ability1',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='charac2',
            new_name='ability2',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='charac3',
            new_name='hidden_ability',
        ),
        migrations.RemoveField(
            model_name='item',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='item',
            name='type1',
            field=models.CharField(max_length=50, verbose_name='タイプ１'),
        ),
        migrations.AlterField(
            model_name='item',
            name='type2',
            field=models.CharField(max_length=50, verbose_name='タイプ２'),
        ),
    ]
