# Generated by Django 3.0.5 on 2020-05-09 04:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200509_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='a',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='A'),
        ),
        migrations.AlterField(
            model_name='item',
            name='ability1',
            field=models.CharField(max_length=50, verbose_name='とくせい１'),
        ),
        migrations.AlterField(
            model_name='item',
            name='b',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='B'),
        ),
        migrations.AlterField(
            model_name='item',
            name='c',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='C'),
        ),
        migrations.AlterField(
            model_name='item',
            name='d',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='D'),
        ),
        migrations.AlterField(
            model_name='item',
            name='h',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='H'),
        ),
        migrations.AlterField(
            model_name='item',
            name='no',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='図鑑番号'),
        ),
        migrations.AlterField(
            model_name='item',
            name='s',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='S'),
        ),
        migrations.AlterField(
            model_name='item',
            name='type2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='タイプ２'),
        ),
    ]
