# Generated by Django 3.0.5 on 2020-05-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200509_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='image/')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': '図鑑', 'verbose_name_plural': '図鑑'},
        ),
    ]
