# Generated by Django 3.0.5 on 2020-05-11 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200510_1639'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
